// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<Record<string, any>>;

export function GetHistory():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function RecordAndTranscribe():Promise<string>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function StopRecording():Promise<void>;
