// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRecordingStatus() {
  return window['go']['main']['App']['GetRecordingStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RecordAndTranscribe() {
  return window['go']['main']['App']['RecordAndTranscribe']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}
